Repository seolbin01/sports-agency, pull requests merged in 2024-08, with the labels that each got.

#1 feat: 모든 선수 정보 보기 기능 추가
  src/main/java/com/synergy/sports_agency/aggregate/Grade.java
  src/main/java/com/synergy/sports_agency/aggregate/Player.java
  src/main/java/com/synergy/sports_agency/repository/PlayerRepository.java
  src/main/java/com/synergy/sports_agency/run/Application.java
  src/main/java/com/synergy/sports_agency/service/PlayerService.java
Labels: enhancement

#2 feat: 선수 찾기 기능 추가
  src/main/java/com/synergy/sports_agency/repository/PlayerRepository.java
  src/main/java/com/synergy/sports_agency/run/Application.java
  src/main/java/com/synergy/sports_agency/service/PlayerService.java
Labels: enhancement

#7 프로그램 종료 출력문 수정
  src/main/java/com/synergy/sports_agency/aggregate/Player.java
  src/main/java/com/synergy/sports_agency/repository/PlayerRepository.java
  src/main/java/com/synergy/sports_agency/run/Application.java
  src/main/java/com/synergy/sports_agency/service/PlayerService.java
  src/main/java/com/synergy/sports_agency/stream/MyObjectOutPutStream.java
Labels: enhancement

#4 선수 등록 기능 추가
  src/main/java/com/synergy/sports_agency/aggregate/Player.java
  src/main/java/com/synergy/sports_agency/repository/PlayerRepository.java
  src/main/java/com/synergy/sports_agency/run/Application.java
  src/main/java/com/synergy/sports_agency/service/PlayerService.java
  src/main/java/com/synergy/sports_agency/stream/MyObjectOutPutStream.java
Labels: enhancement

#5 선수 정보 수정 기능 추가
  src/main/java/com/synergy/sports_agency/aggregate/Player.java
  src/main/java/com/synergy/sports_agency/repository/PlayerRepository.java
  src/main/java/com/synergy/sports_agency/run/Application.java
  src/main/java/com/synergy/sports_agency/service/PlayerService.java
  src/main/java/com/synergy/sports_agency/stream/MyObjectOutPutStream.java
Labels: enhancement

#9 docs: README.md 추가
  README.md
  image/soccer.png
Labels: documentation

#10 docs: README.md 수정
  README.md
  image/soccer.png
Labels: documentation

#11 docs: README.md 수정
  README.md
Labels: documentation

#12 docs: README.md 수정
  README.md
Labels: documentation

#13 feat: 종목별 최고(등급) 선수 찾기 기능
  src/main/java/com/synergy/sports_agency/repository/PlayerRepository.java
  src/main/java/com/synergy/sports_agency/run/Application.java
  src/main/java/com/synergy/sports_agency/service/PlayerService.java
Labels: enhancement

#14 feat: 모든 선수 평균 연봉 보기 추가
  src/main/java/com/synergy/sports_agency/repository/PlayerRepository.java
  src/main/java/com/synergy/sports_agency/run/Application.java
  src/main/java/com/synergy/sports_agency/service/PlayerService.java
Labels: enhancement

#15 fix: 모든 선수 평균 연봉 기능 수정
  src/main/java/com/synergy/sports_agency/repository/PlayerRepository.java
  src/main/java/com/synergy/sports_agency/run/Application.java
  src/main/java/com/synergy/sports_agency/service/PlayerService.java
Labels: bug

#16 feat: 종목별 평균 신장 보기 기능 추가
  src/main/java/com/synergy/sports_agency/repository/PlayerRepository.java
  src/main/java/com/synergy/sports_agency/run/Application.java
  src/main/java/com/synergy/sports_agency/service/PlayerService.java
Labels: enhancement

#17 feat: MZ세대 선수 중 가장 가벼운 선수 찾기 기능 추가
  src/main/java/com/synergy/sports_agency/repository/PlayerRepository.java
  src/main/java/com/synergy/sports_agency/run/Application.java
  src/main/java/com/synergy/sports_agency/service/PlayerService.java
Labels: enhancement

#18 feat: 모든 선수 목록(선수명) 기능 추가
  src/main/java/com/synergy/sports_agency/repository/PlayerRepository.java
  src/main/java/com/synergy/sports_agency/run/Application.java
  src/main/java/com/synergy/sports_agency/service/PlayerService.java
Labels: enhancement

#19 feat: 내년 연봉 미리보기 기능 추가
  src/main/java/com/synergy/sports_agency/run/Application.java
  src/main/java/com/synergy/sports_agency/service/PlayerService.java
Labels: enhancement

#20 feat: 특정 선수 BMI 체크 후 연봉 조정 기능 추가
  src/main/java/com/synergy/sports_agency/run/Application.java
  src/main/java/com/synergy/sports_agency/service/PlayerService.java
Labels: enhancement

#21 feat: 부상 관리 기능 추가
  src/main/java/com/synergy/sports_agency/run/Application.java
  src/main/java/com/synergy/sports_agency/service/PlayerService.java
Labels: enhancement

#22 feat: 미성년자 선수 연봉 제한 기능 추가
  src/main/java/com/synergy/sports_agency/run/Application.java
  src/main/java/com/synergy/sports_agency/service/PlayerService.java
Labels: enhancement

#24 feat: 특정 년도에 따른 성인 선수 선별
  src/main/java/com/synergy/sports_agency/run/Application.java
  src/main/java/com/synergy/sports_agency/service/PlayerService.java
Labels: enhancement

#25 refactor: 종목별 최고 선수 찾기 수정
  src/main/java/com/synergy/sports_agency/repository/PlayerRepository.java
  src/main/java/com/synergy/sports_agency/service/PlayerService.java
Labels: duplicate, enhancement

#27 refactor: 평균 연봉 보기 수정
  src/main/java/com/synergy/sports_agency/repository/PlayerRepository.java
  src/main/java/com/synergy/sports_agency/service/PlayerService.java
Labels: duplicate, enhancement

#28 refactor: 종목별 평균 신장 보기 수정
  src/main/java/com/synergy/sports_agency/repository/PlayerRepository.java
  src/main/java/com/synergy/sports_agency/service/PlayerService.java
Labels: duplicate, enhancement

#29 refactor: 모든 선수 목록 수정
  src/main/java/com/synergy/sports_agency/repository/PlayerRepository.java
  src/main/java/com/synergy/sports_agency/service/PlayerService.java
Labels: duplicate, enhancement

#30 refactor: MZ세대 선수 중 가장 가벼운 선수 찾기
  src/main/java/com/synergy/sports_agency/repository/PlayerRepository.java
  src/main/java/com/synergy/sports_agency/service/PlayerService.java
Labels: duplicate, enhancement
